#!/usr/bin/env bash

source "$HOME/dotfiles/sketchybar/shared/utils.sh"

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$HOME/dotfiles/sketchybar/plugins"
FONT_FACE="RobotoMono Nerd Font"
FONT_COLOR="0xffe0b3ff"
ICON_COLOR="0xffe835f7"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

# Workaround for now to set correct bar height on macbook
# TODO: move bar creation logic into a separate function
MONITOR=$(/opt/homebrew/bin/aerospace list-monitors | awk 'NR==1 {print $3}')

if [[ "$MONITOR" == "Built-in" ]]; then
  BAR_HEIGHT=40
else
  BAR_HEIGHT=25
fi

sketchybar --bar position=top height=$BAR_HEIGHT blur_radius=30 color=0x40000000

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="$FONT_FACE:Bold:17.0"
  label.font="$FONT_FACE:Regular:14.0"
  icon.color=$ICON_COLOR
  label.color=$FONT_COLOR
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item chevron left \
	--set chevron icon=󰏚  icon.padding_right=0 icon.padding_left=0 label.drawing=off \
	--add item front_app left \
	--set front_app icon.drawing=off label.padding_left=0 script="$PLUGIN_DIR/front_app.sh" \
	--subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
	--set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
	--add item volume right \
	--set volume script="$PLUGIN_DIR/volume.sh" \
	--subscribe volume volume_change \
	--add item battery right \
	--set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
	--subscribe battery system_woke power_source_change \
	--add item cpu right \
	--set cpu update_freq=2 icon=  script="$PLUGIN_DIR/cpu.sh"

##### Aerospace workspace indicator & toggle #####
sketchybar --add event aerospace_workspace_change
sketchybar --add item current_space left \
  --set current_space \
    label="…" \
    icon=󰏚  \
    background.corner_radius=5 \
    background.height=30 \
    background.color=0xff7048a4 \
    script="$PLUGIN_DIR/aerospace_event_handler.sh" \
  --subscribe current_space mouse.clicked aerospace_workspace_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update